name: Build and Deploy APK

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust Python version as needed

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer
          sudo apt-get install -y \
            build-essential \
            git \
            python3 \
            zlib1g-dev \
            openjdk-8-jdk

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-kivy-app.apk  # Adjust APK name if needed
          path: ./bin/
